routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => 'auth'], function () {
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories','CategoryController');
Route::get('/categories/publish/{id}','CategoryController@publish')->name('categories.publish');
Route::get('/categories/draft/{id}','CategoryController@draft')->name('categories.draft');

Route::resource('product','ProductController');
Route::get('/product/publish/{id}','ProductController@publish')->name('product.publish');
Route::get('/product/draft/{id}','ProductController@draft')->name('product.draft');
Route::get('/product/search/{id}', 'ProductController@search');

Route::resource('stock','StockController');
Route::resource('transaction','TransactionController')->except(['edit','update','destroy']);
Route::get('/transaction/search/{id}', 'TransactionController@search');

Route::resource('refund','RefundController')->except(['edit','update','destroy','show']);
});

resources/views/produk/create.blade.php
@extends('layouts.master')

@section('content')
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <form id="signupForm" action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                <h4 class="form-header text-uppercase">
                  <i class="fa fa-bars"></i>
                   Tambah Data Produk
                </h4>

                @if (session('status'))
                <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <div class="alert-icon contrast-alert">
                         <i class="icon-check"></i>
                        </div>
                        <div class="alert-message">
                          <span><strong>Success!</strong> {{ session('status') }}</span>
                        </div>
                      </div> 
                @endif
                

                <div class="form-group row">
                        {{-- <input type="text" class="form-control" id="input-10" name="stok" value="0"> --}}
                        <label for="input-10" class="col-sm-2 col-form-label">Nama Produk</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control" id="input-10" name="name">
                        </div>
                        <label for="input-11" class="col-sm-2 col-form-label">Kategori</label>
                        <div class="col-sm-4">
                            <select name="category_id" class="form-control single-select" id="basic-select">
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ ucwords($category->name) }}</option>
                                @endforeach
                            </select>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="input-12" class="col-sm-2 col-form-label">Harga</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control" id="input-12" name="price">
                        </div>
                        <label for="input-13" class="col-sm-2 col-form-label">Warna</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control" id="input-13" name="color">
                        </div>
                      </div>
                      {{-- <h4 class="form-header text-uppercase">
                      <i class="fa fa-envelope-o"></i>
                        Contact Info & Bio
                      </h4> --}}
      
                      <div class="form-group row">
                        <label for="input-14" class="col-sm-2 col-form-label">Gambar</label>
                        <div class="col-sm-4">
                          <input type="file" class="form-control" id="image" name="image" placeholder="Enter image" value="{{ old('image') }}"  required>
                        </div>
                        <label for="input-15" class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-4">
                                <select class="form-control" id="basic-select" name="status" >
                                        <option value="publish">Publish</option>
                                        <option value="draft">Draft</option>
                                      </select>
                        </div>
                      </div>
                      
                      <div class="form-group row">
                        <label for="input-17" class="col-sm-2 col-form-label">Deskripsi</label>
                        <div class="col-sm-10">
                          <textarea class="form-control" name="description" rows="4" id="input-17"></textarea>
                        </div>
                      </div>
                      <div class="form-footer">
                          <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i> CANCEL</button>
                          <button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> SAVE</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div><!--End Row-->

@endsection

@section('top')
<!--Select Plugins-->
<link href="{{ asset('assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet" />
@endsection

@section('bot')
<!--Select Plugins Js-->
<script src="{{  asset('assets/plugins/select2/js/select2.min.js') }}"></script>

<script>
    $(document).ready(function() {
        $('.single-select').select2();



      });

</script>


<!--Form Validatin Script-->
<script src="{{ asset('assets/plugins/jquery-validation/js/jquery.validate.min.js') }}"></script>
<script>

        $().ready(function() {
    
        $("#personal-info").validate();
    
       // validate signup form on keyup and submit
        $("#signupForm").validate({
            rules: {
                category_id: "required",
                // image: "required",
                status: "required",
                name: {
                    required: true,
                    minlength: 3
                },
                price: {
                    required: true,
                    minlength: 3,
                },
                color: {
                    required: true,
                    minlength: 3,
                },
                description: {
                    required: true,
                    minlength:5,
                },
            },
            messages: {
                category_id: "Mohon, masukan kategori produk",
                // image: "Mohon, upload gambar produk",
                status: "Mohon masukan status produk",
                name: {
                    required: "Mohon, masukan nama produk",
                    minlength: "Nama produk minimal harus 3 digit"
                },
                price: {
                    required: "Mohon, masukan harga produk",
                    minlength: "Nama produk minimal harus 3 digit"
                },
                color: {
                    required: "Mohon, masukan warna produk",
                    minlength: "Nama produk minimal harus 3 digit"
                },
                description: {
                    required: "Mohon, masukan deskirpsi produk",
                    minlength: "Nama produk minimal harus 5 digit"
                },
            }
        });
    
    });
    
        </script>

@endsection

resources/views/produk/edit.blade.php
@extends('layouts.master')

@section('content')
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <form action="{{ route('product.update', ['id'=> $product->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                <h4 class="form-header text-uppercase">
                  <i class="fa fa-bars"></i>
                   Ubah Data Produk
                </h4>

                @if (session('status'))
                <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <div class="alert-icon contrast-alert">
                         <i class="icon-check"></i>
                        </div>
                        <div class="alert-message">
                          <span><strong>Success!</strong> {{ session('status') }}</span>
                        </div>
                      </div> 
                @endif
                
                <input type="hidden" name="id" value="{{ $product->id }}">

                <div class="form-group row">
                        <label for="input-10" class="col-sm-2 col-form-label">Nama Produk</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control" id="input-10" name="name" value="{{ old('name')? old('name'):$product->name }}">
                        </div>
                        <label for="input-11" class="col-sm-2 col-form-label">Kategori</label>
                        <div class="col-sm-4">
                            <select name="category_id" class="form-control" id="basic-select">
                                @foreach($categories as $category)
                                <option value="{{ $category->id }}" {{ ($product->category_id == $category->id) ? 'selected' : '' }}>{{ ucwords($category->name) }}</option>
                                @endforeach
                            </select>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="input-12" class="col-sm-2 col-form-label">Harga</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control" id="input-12" name="price" value="{{ old('price')? old('price'):$product->price }}">
                        </div>
                        <label for="input-13" class="col-sm-2 col-form-label">Warna</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control" id="input-13" name="color" value="{{ old('color')? old('color'):$product->color }}">
                        </div>
                      </div>
                      {{-- <h4 class="form-header text-uppercase">
                      <i class="fa fa-envelope-o"></i>
                        Contact Info & Bio
                      </h4> --}}
      
                      <div class="form-group row">
                        <label for="input-14" class="col-sm-2 col-form-label">Gambar</label>
                        <div class="col-sm-4">
                          <input type="file" class="form-control" id="image" name="image" placeholder="Enter image" value="{{ old('image') }}"  >
                        </div>
                        <label for="input-15" class="col-sm-2 col-form-label">Status</label>
                        <div class="col-sm-4">
                                <select class="form-control" id="basic-select" name="status" >
                                        <option {{ $product->status=='publish'?'selected':'' }} value="publish">Publish</option>
                                        <option {{ $product->status=='draft'?'selected':'' }} value="draft">Draft</option>
                                      </select>
                        </div>
                      </div>
                      
                      <div class="form-group row">
                        <label for="input-17" class="col-sm-2 col-form-label">Deskripsi</label>
                        <div class="col-sm-10">
                          <textarea class="form-control" name="description" rows="4" id="input-17">{{ old('description')? old('description'):$product->description }}</textarea>
                        </div>
                      </div>
                      <div class="form-footer">
                          <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i> CANCEL</button>
                          <button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> SAVE</button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div><!--End Row-->

@endsection

@section('top')
@endsection

@section('bot')
<!--Form Validatin Script-->
<script src="{{ asset('assets/plugins/jquery-validation/js/jquery.validate.min.js') }}"></script>
<script>

        $().ready(function() {
    
        $("#personal-info").validate();
    
       // validate signup form on keyup and submit
        $("#signupForm").validate({
            rules: {
                category_id: "required",
                // image: "required",
                status: "required",
                name: {
                    required: true,
                    minlength: 3
                },
                price: {
                    required: true,
                    minlength: 3,
                },
                color: {
                    required: true,
                    minlength: 3,
                },
                description: {
                    required: true,
                    minlength:5,
                },
            },
            messages: {
                category_id: "Mohon, masukan kategori produk",
                // image: "Mohon, upload gambar produk",
                status: "Mohon masukan status produk",
                name: {
                    required: "Mohon, masukan nama produk",
                    minlength: "Nama produk minimal harus 3 digit"
                },
                price: {
                    required: "Mohon, masukan harga produk",
                    minlength: "Nama produk minimal harus 3 digit"
                },
                color: {
                    required: "Mohon, masukan warna produk",
                    minlength: "Nama produk minimal harus 3 digit"
                },
                description: {
                    required: "Mohon, masukan deskirpsi produk",
                    minlength: "Nama produk minimal harus 5 digit"
                },
            }
        });
    
    });
    
        </script>

@endsection

resources/views/produk/index.blade.php
@extends('layouts.master') 
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header"><i class="fa fa-table"></i>Data Produk</div>
            <div class="card-body">
                <a href="{{ route('product.create') }}"><button type="button" class="btn btn-primary waves-effect waves-light m-1">Tambah Data</button></a><br><br>               
                 
                <form action="{{route('product.index')}}">

                    <div class="form-group row">
                        <div class="col-sm-2">
                            <input type="text" class="form-control" placeholder="Nama Produk" value="{{Request::get('name')}}"
                                name="name">

                        </div>

                        <div class="col-sm-2">
                            <input type="text" class="form-control" placeholder="Min Harga" value="{{Request::get('min_price')}}"
                                name="min_price">

                        </div>

                        <div class="col-sm-2">
                            <input type="text" class="form-control" placeholder="Max Harga" value="{{Request::get('max_price')}}"
                                name="max_price">

                        </div>

                        <div class="col-sm-2">
                            <select class="form-control" id="basic-select" name="status">
                                <option value="">Pilih Status</option>
                                <option name="publish">Publish</option>
                                <option name="draft">Draft</option>
                            </select>
                        </div>

                        <div class="col-sm-2">
                            <select name="category_id" class="form-control" id="basic-select">
                                    <option value="">Pilih Kategori</option>
                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}">{{ ucwords($category->name) }}</option>
                                @endforeach
                            </select>
                        </div>

                        <div class="col-sm-2">
                            <input type="submit" value="Search / Filter" class="btn btn-primary">
                        </div>
                    </div>

                </form> 
                
                @if (session('status'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <div class="alert-icon contrast-alert">
                        <i class="icon-check"></i>
                    </div>
                    <div class="alert-message">
                        <span><strong>Success!</strong> {{ session('status') }}</span>
                    </div>
                </div>
                @endif


                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead class="thead-info shadow-info">
                            <tr>
                                <th>Id</th>
                                <th>Stok</th>
                                {{-- <th>Deskripsi</th> --}}
                                <th>Nama</th>
                                <th>Harga</th>
                                <th>Gambar</th>
                                <th>Warna</th>
                                <th>Kategori</th>
                                <th>Status</th>
                                {{--
                                <th>Created At</th>
                                <th>Updated At</th> --}}
                                <th width="20px"></th>
                                <th width="70px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @php
                                $no =1;
                            @endphp
                            @foreach ($products as $product)
                            <tr>
                                <td>{{ $no++ }}</td>
                                <td>{{ $product->stok }}</td>
                                <td>{{ ucwords($product->name) }}</td>
                                {{-- <td>{{ $product->description }}</td> --}}
                                <td>Rp.{{  number_format($product->price,0) }}</td>
                                <td><img class="rounded-square" width="50" height="50" src="{{ url($product->image) }}" alt="gambar produk"></td>
                                <td>{{ $product->color }}</td>
                                <td>{{ $product->category->name }}</td>
                                <td>
                                    @if ($product->status == 'publish')
                                    <button type="button" class="btn btn-inverse-primary waves-effect btn-sm">{{ $product->status }}</button>                                    @elseif ($product->status == 'draft')
                                    <button type="button" class="btn btn-inverse-danger waves-effect btn-sm">{{ $product->status }}</button>                                    @endif
                                </td>
                                {{--
                                <td>{{ $product->created_at }}</td>
                                <td>{{ $product->updated_at }}</td> --}}
                                <td>
                                    <a href="{{ url('/product/publish/'.$product->id) }}" class="btn btn-gradient-bloody btn-sm">Publish</a>
                                    <a href="{{ url('/product/draft/'.$product->id) }}" class="btn btn-gradient-scooter btn-sm">Draft</a>

                                    <a href="{{ route('product.edit', ['id' => $product->id]) }}" class="btn btn-gradient-purpink btn-sm">Ubah</a>
                                </td>
                                <td>
                                    <form class="d-inline" action="{{route('product.destroy', ['id' => $product->id])}}" method="POST" onsubmit="return confirm('Anda yakin akan menghapus data ini dan memindahkan ke tong sampah ?')">

                                        @csrf

                                        <input type="hidden" value="DELETE" name="_method">

                                        <input type="submit" class="btn btn-gradient-ibiza btn-sm" value="Hapus">

                                    </form>
                                </td>
                                <tr>
                                    @endforeach
                        </tbody>
                        {{--
                        <tfoot class="thead-danger shadow-danger">
                            <th>ID</th>
                            <th>Name</th>
                            <th>Slug</th>
                            <th>Created At</th>
                            <th>Updated At</th>
                        </tfoot> --}}
                    </table>
                    <br> {{ $products->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Row-->
@endsection
 
@section('top')
<!--Data Tables -->
<link href="{{ asset('assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/plugins/bootstrap-datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
@endsection
 
@section('bot')
<!--Data Tables js-->
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/jszip.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/pdfmake.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/vfs_fonts.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.html5.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.print.min.js') }}"></script>
<script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.colVis.min.js') }}"></script>

<script>
    $(document).ready(function() {
             //Default data table
              $('#default-datatable').DataTable();
       
       
              var table = $('#example').DataTable( {
               lengthChange: false,
               buttons: [ 'copy', 'excel', 'pdf', 'print', 'colvis' ]
             } );
        
            table.buttons().container()
               .appendTo( '#example_wrapper .col-md-6:eq(0)' );
             
             } );
</script>
@endsection