routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => 'auth'], function () {
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories','CategoryController');
Route::get('/categories/publish/{id}','CategoryController@publish')->name('categories.publish');
Route::get('/categories/draft/{id}','CategoryController@draft')->name('categories.draft');

Route::resource('product','ProductController');
Route::get('/product/publish/{id}','ProductController@publish')->name('product.publish');
Route::get('/product/draft/{id}','ProductController@draft')->name('product.draft');
Route::get('/product/search/{id}', 'ProductController@search');

Route::resource('stock','StockController');
Route::resource('transaction','TransactionController')->except(['edit','update','destroy']);
Route::get('/transaction/search/{id}', 'TransactionController@search');

Route::resource('refund','RefundController')->except(['edit','update','destroy','show']);
});

resources/views/stok/create.blade.php
@extends('layouts.master')

@section('content')
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <form id="signupForm" action="{{ route('stock.store') }}" method="POST">
                    @csrf
                <h4 class="form-header text-uppercase">
                  <i class="fa fa-bars"></i>
                   Tambah Data Stok
                </h4>

                @if (session('status'))
                <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <div class="alert-icon contrast-alert">
                         <i class="icon-check"></i>
                        </div>
                        <div class="alert-message">
                          <span><strong>Success!</strong> {{ session('status') }}</span>
                        </div>
                      </div> 
                @endif
                
                <div class="form-group row">
                        <label for="input-11" class="col-sm-2 col-form-label">Nama Produk</label>
                        <div class="col-sm-4">
                            <select name="product_id" class="form-control single-select" id="basic-select">
                                @foreach($products as $product)
                                    <option value="{{ $product->id }}">{{ ucwords($product->name) }}</option>
                                @endforeach
                            </select>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="input-12" class="col-sm-2 col-form-label">Stok</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control" id="input-12" name="stok">
                        </div>
                      </div>

                    <div class="form-footer">
                            <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i> CANCEL</button>
                            <button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> SAVE</button>
                    </div>
                        
                    </form>
                  </div>
                </div>
              </div>
            </div><!--End Row-->

@endsection

@section('top')
  <link href="{{ asset('assets/plugins/select2/css/select2.min.css') }}" rel="stylesheet" />
@endsection

@section('bot')

<script src="{{  asset('assets/plugins/select2/js/select2.min.js') }}"></script>

<script>
    $(document).ready(function() {
        $('.single-select').select2();
      });
</script>

<!--Form Validatin Script-->
<script src="{{ asset('assets/plugins/jquery-validation/js/jquery.validate.min.js') }}"></script>
<script>

        $().ready(function() {
    
        // $("#form-stok").validate();
    
       // validate signup form on keyup and submit
        $("#signupForm").validate({
            rules: {
                product_id: "required",
                stok: "required",
            },
            messages: {
                product_id: "Mohon, masukan data produk",
                stok: "Mohon, masukan stok produk",
            }
        });
    
    });
    
        </script>

@endsection

resources/views/stok/edit.blade.php
@extends('layouts.master')

@section('content')
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <form id="signupForm" action="{{ route('stock.update', ['id'=> $stock->id]) }}" method="POST">
                    @csrf
                    @method('PUT')
                <h4 class="form-header text-uppercase">
                  <i class="fa fa-bars"></i>
                   Edit Data Stok
                </h4>

                @if (session('status'))
                <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <div class="alert-icon contrast-alert">
                         <i class="icon-check"></i>
                        </div>
                        <div class="alert-message">
                          <span><strong>Success!</strong> {{ session('status') }}</span>
                        </div>
                      </div> 
                @endif
                
                <input type="hidden" name="id" value="{{ $stock->id }}">

                <div class="form-group row">
                        <label for="input-11" class="col-sm-2 col-form-label">Kategori</label>
                        <div class="col-sm-4">
                            <select name="product_id" class="form-control" id="basic-select">
                                @foreach($products as $product)
                                <option value="{{ $product->id }}" {{ ($stock->product_id == $product->id) ? 'selected' : '' }}>{{ ucwords($product->name) }}</option>
                                @endforeach
                            </select>
                        </div>
                      </div>
                      <div class="form-group row">
                        <label for="input-12" class="col-sm-2 col-form-label">Stok</label>
                        <div class="col-sm-4">
                          <input type="text" class="form-control" id="input-12" name="stok" value="{{ old('stok')? old('stok'):$stock->stok }}">
                        </div>
                      </div>

                    <div class="form-footer">
                            <button type="submit" class="btn btn-danger"><i class="fa fa-times"></i> CANCEL</button>
                            <button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> SAVE</button>
                    </div>
                        
                    </form>
                  </div>
                </div>
              </div>
            </div><!--End Row-->

@endsection

@section('top')
@endsection

@section('bot')
<!--Form Validatin Script-->
<script src="{{ asset('assets/plugins/jquery-validation/js/jquery.validate.min.js') }}"></script>
<script>

        $().ready(function() {
    
        // $("#form-stok").validate();
    
       // validate signup form on keyup and submit
        $("#signupForm").validate({
            rules: {
                product_id: "required",
                stok: "required",
            },
            messages: {
                product_id: "Mohon, masukan data produk",
                stok: "Mohon, masukan stok produk",
            }
        });
    
    });
    
        </script>

@endsection

resources/views/stok/index.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header"><i class="fa fa-table"></i>Data Stok</div>
            <div class="card-body">
                    <a href="{{ route('stock.create') }}"><button type="button" class="btn btn-primary waves-effect waves-light m-1">Tambah Data</button></a><br><br>
              
                     <form action="{{ route('stock.index')}}">

                            <div class="form-group row">
                                    <div class="col-sm-5">
                                        <select name="product_id" class="form-control" id="basic-select">
                                          <option value="">Pilih Produk</option>  
                                          @foreach($products as $p)
                                                <option value="{{ $p->id }}">{{ ucwords($p->name) }}</option>
                                            @endforeach
                                        </select>
          
                                    </div> 
                                    <div class="col-sm-5">
                                        <input 
                                        type="text" 
                                        class="form-control" 
                                        placeholder="cari berdasarkan stok"
                                        value="{{Request::get('stok')}}"
                                        name="stok">
      
                                    </div>
                                    <div class="col-sm-2">
                                            <input 
                                            type="submit" 
                                            value="Search / Filter" 
                                            class="btn btn-primary">
                                    </div>
                                  </div>
                    
                          </form> 

                          @if (session('status'))
                          <div class="alert alert-success alert-dismissible" role="alert">
                                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                                  <div class="alert-icon contrast-alert">
                                   <i class="icon-check"></i>
                                  </div>
                                  <div class="alert-message">
                                    <span><strong>Success!</strong> {{ session('status') }}</span>
                                  </div>
                                </div> 
                          @endif
                          
              
                    <div class="table-responsive">
              <table  class="table table-hover">
                <thead class="thead-info shadow-info">
                    <tr>
                        <th>ID</th>
                        <th>Product</th>
                        <th>Stock</th>
                        {{-- <th>Created At</th>
                        <th>Updated At</th> --}}
                        <th width="20px"></th>
                        <th width="70px"></th>
                    </tr>
                </thead>
                <tbody>
                  @php
                      $no = 1;
                  @endphp
                    @foreach ($stocks as $stock)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ ucwords($stock->product->name) }}</td>
                        <td>{{ $stock->stok }}</td>
                        {{-- <td>{{ $stock->created_at }}</td>
                        <td>{{ $stock->updated_at }}</td> --}}
                       <td>
                            <a href="{{ route('stock.edit', ['id' => $stock->id]) }}" class="btn btn-gradient-purpink btn-sm">Ubah</a>
                        </td>
                            <td>
                                    <form 
                                    class="d-inline"
                                    action="{{route('stock.destroy', ['id' => $stock->id])}}"
                                    method="POST"
                                    onsubmit="return confirm('Anda yakin akan menghapus data ini ?')"
                                    >
                  
                                    @csrf 
                  
                                    <input 
                                      type="hidden" 
                                      value="DELETE" 
                                      name="_method">
                  
                                    <input 
                                      type="submit" 
                                      class="btn btn-gradient-ibiza btn-sm" 
                                      value="Hapus">
                  
                                  </form>
                            </td>
                    <tr>
                    @endforeach
                </tbody>
                {{-- <tfoot class="thead-danger shadow-danger">
                        <th>ID</th>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Created At</th>
                        <th>Updated At</th>
                </tfoot> --}}
                </table>
                <br>
                {{ $stocks->links() }}
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->
@endsection

@section('top')
    <!--Data Tables -->
    <link href="{{ asset('assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/plugins/bootstrap-datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('bot')
<!--Data Tables js-->
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.colVis.min.js') }}"></script>

    <script>
            $(document).ready(function() {
             //Default data table
              $('#default-datatable').DataTable();
       
       
              var table = $('#example').DataTable( {
               lengthChange: false,
               buttons: [ 'copy', 'excel', 'pdf', 'print', 'colvis' ]
             } );
        
            table.buttons().container()
               .appendTo( '#example_wrapper .col-md-6:eq(0)' );
             
             } );
       
           </script>
@endsection