routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => 'auth'], function () {
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories','CategoryController');
Route::get('/categories/publish/{id}','CategoryController@publish')->name('categories.publish');
Route::get('/categories/draft/{id}','CategoryController@draft')->name('categories.draft');

Route::resource('product','ProductController');
Route::get('/product/publish/{id}','ProductController@publish')->name('product.publish');
Route::get('/product/draft/{id}','ProductController@draft')->name('product.draft');
Route::get('/product/search/{id}', 'ProductController@search');

Route::resource('stock','StockController');
Route::resource('transaction','TransactionController')->except(['edit','update','destroy']);
Route::get('/transaction/search/{id}', 'TransactionController@search');

Route::resource('refund','RefundController')->except(['edit','update','destroy','show']);
});

resources/views/kategori/create.blade.php
@extends('layouts.master')

@section('content')
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <form id="signupForm" action="{{ route('categories.store') }}" method="POST">
                    @csrf
                <h4 class="form-header text-uppercase">
                  <i class="fa fa-bars"></i>
                   Tambah Data Kategori
                </h4>

                @if (session('status'))
                <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <div class="alert-icon contrast-alert">
                         <i class="icon-check"></i>
                        </div>
                        <div class="alert-message">
                          <span><strong>Success!</strong> {{ session('status') }}</span>
                        </div>
                      </div> 
                @endif
                

                <div class="form-group row">
                  <label for="input-10" class="col-sm-2 col-form-label">Nama Kategori</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="input-10" name="name" value="{{ old('name') }}">
                <div class="form-footer">
                    <button type="reset" class="btn btn-danger"><i class="fa fa-times"></i> RESET</button>
                    <button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> SAVE</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div><!--End Row-->

@endsection

@section('top')
@endsection

@section('bot')
<!--Form Validatin Script-->
<script src="{{ asset('assets/plugins/jquery-validation/js/jquery.validate.min.js') }}"></script>
<script>

$().ready(function() {

$("#personal-info").validate();

// validate signup form on keyup and submit
$("#signupForm").validate({
    rules: {
        name: {
                required: true,
                minlength: 3
            },
    },
    messages: {
        name: {
            required: "Mohon, masukan nama kategori",
            minlength: "Nama kategori minimal harus 3 digit"
        },
    }
});

});

</script>

@endsection

resources/views/kategori/edit.blade.php
@extends('layouts.master')

@section('content')
      <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <form id="signupForm" action="{{ route('categories.update',['id' => $category->id]) }}" method="POST">
                    @csrf
                    @method('PUT')
                <h4 class="form-header text-uppercase">
                  <i class="fa fa-bars"></i>
                   Edit Data Kategori
                </h4>

                @if (session('status'))
                <div class="alert alert-success alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <div class="alert-icon contrast-alert">
                         <i class="icon-check"></i>
                        </div>
                        <div class="alert-message">
                          <span><strong>Success!</strong> {{ session('status') }}</span>
                        </div>
                      </div> 
                @endif
                

                <div class="form-group row">
                  <label for="input-10" class="col-sm-2 col-form-label">Nama Kategori</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="input-10" name="name" value="{{old('name') ? old('name') : $category->name}}" >
                <div class="form-footer">
                    <button type="reset" class="btn btn-danger"><i class="fa fa-times"></i> RESET</button>
                    <button type="submit" class="btn btn-success"><i class="fa fa-check-square-o"></i> SAVE</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div><!--End Row-->

@endsection

@section('top')
@endsection

@section('bot')
<!--Form Validatin Script-->
<script src="{{ asset('assets/plugins/jquery-validation/js/jquery.validate.min.js') }}"></script>
<script>

$().ready(function() {

$("#personal-info").validate();

// validate signup form on keyup and submit
$("#signupForm").validate({
    rules: {
        name: {
                required: true,
                minlength: 3
            },
    },
    messages: {
        name: {
            required: "Tolong masukan nama kategori",
            minlength: "Nama kategori minimal 3 digit"
        },
    }
});

});

</script>

@endsection

resources/views/kategori/index.blade.php
@extends('layouts.master')

@section('content')
<div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-header"><i class="fa fa-table"></i>Data Kategori</div>
            <div class="card-body">
                    <a href="{{ route('categories.create') }}"><button type="button" class="btn btn-primary waves-effect waves-light m-1">Tambah Data</button></a><br><br>
              
                    <form action="{{route('categories.index')}}">

                            <div class="form-group row">
                                    <div class="col-sm-5">
                                            <input 
                                            type="text" 
                                            class="form-control" 
                                            placeholder="cari data berdasarkan nama kategori"
                                            value="{{Request::get('name')}}"
                                            name="name">
          
                                    </div>
                                    <div class="col-sm-5">
                                            <select class="form-control" id="basic-select" name="status">
                                                    <option value="">Pilih status</option>
                                                    <option value="publish">Publish</option>
                                                    <option value="draft">Draft</option>
                                                  </select>
                                    </div>
                                    <div class="col-sm-2">
                                            <input 
                                            type="submit" 
                                            value="Search / Filter" 
                                            class="btn btn-primary">
                                    </div>
                                  </div>
                    
                          </form>
                          @if (session('status'))
                          <div class="alert alert-success alert-dismissible" role="alert">
                                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                                  <div class="alert-icon contrast-alert">
                                   <i class="icon-check"></i>
                                  </div>
                                  <div class="alert-message">
                                    <span><strong>Success!</strong> {{ session('status') }}</span>
                                  </div>
                                </div> 
                          @endif
                          
              
                    <div class="table-responsive">
              <table  class="table table-hover">
                <thead class="thead-info shadow-info">
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Slug</th>
                        {{-- <th>Created At</th>
                        <th>Updated At</th> --}}
                        <th>Status</th>
                        <th width="20px"></th>
                        <th width="70px"></th>
                    </tr>
                </thead>
                <tbody>
                  @php
                      $no = 1;
                  @endphp
                    @foreach ($categories as $category)
                    <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ ucwords($category->name) }}</td>
                        <td>{{ $category->slug }}</td>
                        <td>
                            @if ($category->status == 'publish')
                                <button type="button" class="btn btn-inverse-primary waves-effect btn-sm">{{ $category->status }}</button>
                            @elseif ($category->status == 'draft')
                            <button type="button" class="btn btn-inverse-danger waves-effect btn-sm">{{ $category->status }}</button>
                            @endif
                        </td>
                        {{-- <td>{{ $category->created_at }}</td>
                        <td>{{ $category->updated_at }}</td> --}}
                       <td>
                            <a href="{{ url('/categories/publish/'.$category->id) }}" class="btn btn-gradient-bloody btn-sm">Publish</a>
                            <a href="{{ url('/categories/draft/'.$category->id) }}" class="btn btn-gradient-scooter btn-sm">Draft</a>

                            <a href="{{ route('categories.edit', ['id' => $category->id]) }}" class="btn btn-gradient-purpink btn-sm">Ubah</a>
                        </td>
                            <td>
                                    <form 
                                    class="d-inline"
                                    action="{{route('categories.destroy', ['id' => $category->id])}}"
                                    method="POST"
                                    onsubmit="return confirm('Anda yakin akan menghapus data ini dan memindahkan ke tong sampah ?')"
                                    >
                  
                                    @csrf 
                  
                                    <input 
                                      type="hidden" 
                                      value="DELETE" 
                                      name="_method">
                  
                                    <input 
                                      type="submit" 
                                      class="btn btn-gradient-ibiza btn-sm" 
                                      value="Hapus">
                  
                                  </form>
                            </td>
                    <tr>
                    @endforeach
                </tbody>
                {{-- <tfoot class="thead-danger shadow-danger">
                        <th>ID</th>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Created At</th>
                        <th>Updated At</th>
                </tfoot> --}}
                </table>
                <br>
                {{ $categories->links() }}
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->
@endsection

@section('top')
    <!--Data Tables -->
    <link href="{{ asset('assets/plugins/bootstrap-datatable/css/dataTables.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('assets/plugins/bootstrap-datatable/css/buttons.bootstrap4.min.css') }}" rel="stylesheet" type="text/css">
@endsection

@section('bot')
<!--Data Tables js-->
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/jszip.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/pdfmake.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/vfs_fonts.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('assets/plugins/bootstrap-datatable/js/buttons.colVis.min.js') }}"></script>

    <script>
            $(document).ready(function() {
             //Default data table
              $('#default-datatable').DataTable();
       
       
              var table = $('#example').DataTable( {
               lengthChange: false,
               buttons: [ 'copy', 'excel', 'pdf', 'print', 'colvis' ]
             } );
        
            table.buttons().container()
               .appendTo( '#example_wrapper .col-md-6:eq(0)' );
             
             } );
       
           </script>
@endsection